Added TraceID
p-kozlowski/gohan pull request #1
Opened 2017-08-22 11:08 UTC by andriikonstantinov

2017-08-22 13:21 UTC, zimnx approved these changes

2017-08-22 14:28 UTC, przemyslaw-dobrowolski-cl requested changes

2017-08-22 14:28 UTC, przemyslaw-dobrowolski-cl commented on extension/goplugin/environment.go
> +	thisEnvironment.Logger().Debugf("Starting event: %s, schema: %s", event, sch.rawSchema.ID)
Why this log is a part of this commit?

2017-08-22 14:28 UTC, przemyslaw-dobrowolski-cl commented on extension/goplugin/environment.go
> +	//Generating TraceID
In all places, after comment slases there is one space, but not here

2017-08-22 14:28 UTC, przemyslaw-dobrowolski-cl commented on extension/goplugin/environment.go
> +	env.Bind()
Why bind is public? It is dangerous

2017-08-22 15:04 UTC, p-kozlowski requested changes

2017-08-22 15:04 UTC, p-kozlowski commented on extension/goplugin/environment.go
> +	thisEnvironment.Logger().Debugf("Starting event: %s, schema: %s", event, sch.rawSchema.ID)
defer a log message at the end of this function

2017-08-22 15:05 UTC, p-kozlowski commented on extension/goplugin/environment.go
> +	thisEnvironment.Logger().Debugf("Starting event: %s, schema: %s", event, sch.rawSchema.ID)
IMO it's good to have it

2017-08-22 15:16 UTC, andriikonstantinov commented on extension/goplugin/environment.go
> +	thisEnvironment.Logger().Debugf("Starting event: %s, schema: %s", event, sch.rawSchema.ID)
Done

2017-08-22 15:25 UTC, p-kozlowski approved these changes

2017-08-23 08:27 UTC, p-kozlowski commented
@przemyslaw-dobrowolski-cl I'd like to merge this PR. are you satisfied with the changes?

2017-08-24 10:40 UTC, przemyslaw-dobrowolski-cl commented
ok

2017-08-24 10:41 UTC, przemyslaw-dobrowolski-cl approved these changes
ok

2017-08-24 12:02 UTC, merged